---
name: 'Datadog Service Catalog Metadata Provider'
description: 'This is an action which allows you to provide your Datadog Service Catalog metadata to the Datadog Service Catalog'
author: 'Arc XP'
branding:
  icon: 'monitor'
  color: 'blue'
runs:
  using: node16
  main: dist/index.js
inputs:


  github-token:
    description: 'The GitHub token to use for the action; default is `secrets.GITHUB_TOKEN`'
    required: false
  org-rules-file:
    description: 'The path to the org rules file; default is repository `ORG-NAME-HERE/.github` and the `service-catalog-rules.yml` file is expected in the root of that repository.'
    required: false
  datadog-hostname:
    description: 'The Datadog API hostname (this varies by Datadog customer!)'
    required: true
    default: 'api.datadoghq.com'
  datadog-key:
    description: 'The Datadog API key'
    required: true
  datadog-app-key:
    description: 'The Datadog Application key'
    required: true
  schema-version:
    description: 'The version of the Datadog Service Catalog Schema. The default is v2. Valid values are `v2` and `v2.1`.'
    required: false
    default: 'v2'
  service-name:
    description: 'The name of the service'
    required: true
  team:
    description: 'The team responsible for the service'
    required: true
  application:
    description: '(v2.1 only) The name of the application that the service belongs to.'
    required: false
  description:
    description: '(v2.1 only) A description of the service.'
    required: false
  tier:
    description: '(v2.1 only) A representation of how important this service is. You can use any string that conveys meaning for you or your organization.'
    required: false
  lifecycle:
    description: '(v2.1 only) The current life cycle phase of the service. For example: sandbox, staging, production, deprecated'
    required: false
  email:
    description: 'The email address of the team responsible for the service'
    required: true
  slack-support-channel:
    description: 'The slack support channel for the service'
    required: false
  repo:
    description: 'The repository URL for the service. This is a convenience input for when you only have one repository for the service.'
    required: false
  contacts:
    description: 'The contacts for the service'
    required: false
  repos:
    description: 'The repositories for the service'
    required: true
  tags:
    description: 'The tags to apply to the service'
    required: false
  links:
    description: 'The links to related to the service'
    required: false
  docs:
    description: 'The documentation for the service'
    required: false
  integrations:
    description: 'The integrations for the service'
    required: false
