---
name: 'Datadog Service Catalog Metadata Provider'
description: 'This is an action which allows you to provide your Datadog Service Catalog metadata to the Datadog Service Catalog'
author: 'Mike Stemle <hello@mikestemle.com>'
branding:
  icon: 'monitor'
  color: 'purple'
runs:
  using: node20
  main: dist/index.cjs
inputs:
  # Stuff we need for this action
  github-token:
    description: 'The GitHub token to use for the action; default is `secrets.GITHUB_TOKEN`'
    required: false
  org-rules-file:
    description: 'The path to the org rules file; default is repository `ORG-NAME-HERE/.github` and the `service-catalog-rules.yml` file is expected in the root of that repository.'
    required: false
  
  # Stuff we need for the Datadog API
  datadog-hostname:
    description: 'The Datadog API hostname (this varies by Datadog customer!)'
    required: true
    default: 'api.datadoghq.com'
  datadog-key:
    description: 'The Datadog API key'
    required: true
  datadog-app-key:
    description: 'The Datadog Application key'
    required: true
  
  # Fields which are common to all schema versions
  schema-version:
    description: 'The version of the Datadog Service Catalog Schema. For backwards-compatibility reasons, the default is v2. Valid values are `v2` and `v2.1`.'
    required: false
    default: 'v2'
  service-name:
    description: 'The name of the service'
    required: true
  team:
    description: 'The team responsible for the service'
    required: false
  contacts:
    description: 'The contacts for the service'
    required: false
  tags:
    description: 'The tags to apply to the service'
    required: false
  links:
    description: 'The links to related to the service'
    required: false
  integrations:
    description: 'The integrations for the service'
    required: false
  extensions:
    description: 'Any custom extensions you wish to use'
    required: false
  
  # Fields which are unique to v2
  docs:
    description: 'The documentation for the service'
    required: false
  repos:
    description: 'The repositories for the service'
    required: false
  
  # Fields which are unique to v2.1
  application:
    description: '(v2.1 only) The name of the application that the service belongs to.'
    required: false
  description:
    description: '(v2.1 only) A description of the service.'
    required: false
  tier:
    description: '(v2.1 only) A representation of how important this service is. You can use any string that conveys meaning for you or your organization.'
    required: false
  lifecycle:
    description: '(v2.1 only) The current life cycle phase of the service. For example: sandbox, staging, production, deprecated'
    required: false

  # Fields which were added in v2.2
  type:
    description: 'Type of the service. Examples: "web", "db", "cache", "function", "browser", "mobile", "custom"'
    required: false
  languages:
    description: 'A list of programming languages used.'
    required: false
  ci-pipeline-fingerprints:
    description: 'A set of CI pipeline fingerprints related to the service'
    required: false

  # These are convenience inputs which are unique to this action.
  email:
    description: 'The email address of the team responsible for the service'
    required: true
  slack-support-channel:
    description: 'The slack support channel for the service'
    required: false
  repo:
    description: 'The repository URL for the service. This is a convenience input for when you only have one repository for the service.'
    required: false
