---
name: DataDog Service Catalog
on:
  push:
  workflow_dispatch:

runs:
  using: "composite"
  steps:
    - name: Say "Hello"
      shell: bash
      run: |
        echo "Hello, world!"
        pwd
        ls -ltr